[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#151D2C"
textColor = "#F8FAFC"
font = "sans serif"
